# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 400)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(560, 40, 141, 121))
        self.btn_download.setObjectName("btn_download")
        self.lbl_url = QtWidgets.QLabel(self.centralwidget)
        self.lbl_url.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.lbl_url.setObjectName("lbl_url")
        self.lbl_result_log = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result_log.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.lbl_result_log.setObjectName("lbl_result_log")
        self.inp_url = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inp_url.setGeometry(QtCore.QRect(20, 40, 431, 121))
        self.inp_url.setTabChangesFocus(True)
        self.inp_url.setObjectName("inp_url")
        self.out_result_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.out_result_log.setGeometry(QtCore.QRect(20, 190, 681, 151))
        self.out_result_log.setObjectName("out_result_log")
        self.rad_mp4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rad_mp4.setGeometry(QtCore.QRect(470, 50, 80, 16))
        self.rad_mp4.setChecked(True)
        self.rad_mp4.setObjectName("rad_mp4")
        self.rad_flac = QtWidgets.QRadioButton(self.centralwidget)
        self.rad_flac.setGeometry(QtCore.QRect(470, 70, 80, 16))
        self.rad_flac.setObjectName("rad_flac")
        self.rad_wav = QtWidgets.QRadioButton(self.centralwidget)
        self.rad_wav.setGeometry(QtCore.QRect(470, 90, 80, 16))
        self.rad_wav.setObjectName("rad_wav")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inp_url, self.rad_mp4)
        MainWindow.setTabOrder(self.rad_mp4, self.rad_flac)
        MainWindow.setTabOrder(self.rad_flac, self.rad_wav)
        MainWindow.setTabOrder(self.rad_wav, self.btn_download)
        MainWindow.setTabOrder(self.btn_download, self.out_result_log)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube downloader"))
        self.btn_download.setText(_translate("MainWindow", "Download"))
        self.lbl_url.setText(_translate("MainWindow", "URL:"))
        self.lbl_result_log.setText(_translate("MainWindow", "Result log:"))
        self.rad_mp4.setText(_translate("MainWindow", "MP4"))
        self.rad_flac.setText(_translate("MainWindow", "FLAC"))
        self.rad_wav.setText(_translate("MainWindow", "WAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
